// <auto-generated />
using ConsultaPublica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultaPublica.Migrations
{
    [DbContext(typeof(ConsultaPublicaContext))]
    [Migration("20221107155741_testeVorF")]
    partial class testeVorF
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RazorPagesMovie.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AcoesRelevancia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confianca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descreva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterferenciaCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterferenciaComunidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrioridadePoderPublico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("testeVorF")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
